#!/bin/bash

# $Id: marcar_volumen_grabado,v 1.3 2015/07/28 13:51:29 aosorio Exp $
#
# Script para marcar un volúmen como grabado (Archive).
#
# Modo de uso:
#   ./marcar_volumen_grabado <volumen1> [<volumen2> <volumen2> ...]
#

bacula_dir=bacula-dir.terminalquequen.com.ar

set -e

[ $# -eq 0 ] && exit 0

values=""

for volume in $@ ; do
  echo -e "\nMarcando volumen $volume..."
  echo "update volume=$volume set volstatus=Archive" | bconsole > /dev/null
  values="$values, ('$volume', CURRENT_TIMESTAMP)"
done

sql_query="
INSERT INTO tq_volumen_grabado (
    volume,
    fecha_de_grabado)
  VALUES
    $( echo "$values" | sed 's/^, //g' ); "

echo "Actualizando inventario de backup..."
ssh $bacula_dir 'psql -U bacula -c "'$sql_query'"' > /dev/null
echo "Listo"
